Wip/n.bendisch@phytec.de/update pd23.1.0
phytec/meta-celebrity-face-match pull request #5
Opened 2024-10-30 14:19 UTC by s-hemer

This needs to be pulled to a kirkstone branch

2025-01-22 14:09 UTC, s-hemer commented
First do #6

2025-01-24 08:11 UTC, sriedmueller commented
> First do #6

Done.

2025-01-24 08:30 UTC, sriedmueller commented on conf/layer.conf
> +DISTRO_VERSION:append = "-CelebrityFaceMatch-v0.7"
Please put this in a separate update version patch which concludes all your update patches.

2025-01-24 08:30 UTC, sriedmueller commented on recipes-examples/celebrity-face-match/demo-celebrity-face-match_0.3.bb
> +SYSTEMD_AUTO_ENABLE:${PN} = "enable"
The service is enabled by default so technically you don't need this.

2025-01-24 08:30 UTC, sriedmueller commented on conf/layer.conf
> +BBMASK += " meta-freescale-distro/recipes-graphics/wayland/weston-init.bbappend"
Are these mixes of leading whitespaces intentional?

2025-01-24 10:41 UTC, s-hemer commented on conf/layer.conf
> +BBMASK += " meta-freescale-distro/recipes-graphics/wayland/weston-init.bbappend"
Good point, I guess not. The latter two were added by me. Will fix.

2025-01-24 10:48 UTC, s-hemer commented on conf/layer.conf
> +DISTRO_VERSION:append = "-CelebrityFaceMatch-v0.7"
Well but it is an append to the distro version and we switch from hardknott to kirkstone. So it is already something like 0.7.y or 0.7-dev. Agree, that the final 0.7 should conclude ...

2025-01-24 12:02 UTC, sriedmueller commented on conf/layer.conf
> +DISTRO_VERSION:append = "-CelebrityFaceMatch-v0.7"
What about `-CelebrityFaceMatch-kirkstone-dev`?

2025-01-24 12:09 UTC, s-hemer commented on conf/layer.conf
> +DISTRO_VERSION:append = "-CelebrityFaceMatch-v0.7"
Not sure, duplicate encoding as PD23.1.0 already contains this somehow. And string gets longer and longer...

2025-01-24 12:42 UTC, s-hemer commented
Need to review weston.ini change to LVDS display before merge/release.

2025-01-24 13:11 UTC, sriedmueller commented on conf/layer.conf
> +DISTRO_VERSION:append = "-CelebrityFaceMatch-v0.7"
Ok, then `0.7-dev`.

2025-03-11 13:07 UTC, s-hemer commented
No need to keep weston.ini as the changes are just switching HDMI off and LVDS on (default) which should be pretty obvious. Kept the weston.ini masking on separate WIP.

2025-03-13 13:38 UTC, mschwan-phytec requested changes

2025-03-13 13:38 UTC, mschwan-phytec commented on recipes-examples/celebrity-face-match/demo-celebrity-face-match/demo-celebrity-face-match.service
> +Environment="DISPLAY=:0"
This should not be needed, as we are not using X11 but Wayland. Additionally, isn't `XDG_RUNTIME_DIR` required? Have you tested this?

2025-03-14 08:08 UTC, s-hemer commented on recipes-examples/celebrity-face-match/demo-celebrity-face-match/demo-celebrity-face-match.service
> +Environment="DISPLAY=:0"
@NBendisch did the testing of the latest states and also that was installed to the fair demos last year etc. I would vote to anyway just merge it to kirkstone. It is anyways superseeded by your scarthgap release.

2025-03-14 08:13 UTC, mschwan-phytec commented on recipes-examples/celebrity-face-match/demo-celebrity-face-match/demo-celebrity-face-match.service
> +Environment="DISPLAY=:0"
Okay, agreed. We are not planning a kirkstone release, that's true.

2025-03-14 08:13 UTC, merged